name: t6

services:
  app:
    image: mick0974/a13:t6-g12
    container_name: t6-controller
    restart: always
    expose:
      - 8086
    # ports:
    #   - 8083:80
    networks:
      - global-network

networks:
  global-network:
    external: true