name: t9

services:
  app:
    image: mick0974/a13:t9-g19
    container_name: t9-app
    networks:
      - global-network
    volumes:
      - VolumeT9:/VolumeT9

networks:
  global-network:
    external: true

volumes:
  VolumeT9:
    external: true