name: t23

services:
  app:
    image: mick0974/a13:t23-g1
    container_name: t23-controller
    expose:
      - 8082
    depends_on:
      - db
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      DB_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}  # Usa il nome del DB definito nel .env
    networks:
      - global-network

  db:
    image: mysql:latest
    container_name: t23-mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}  # Usa la variabile per la password di root
      MYSQL_DATABASE: ${MYSQL_DATABASE}  # Usa il nome del database
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - global-network
    restart: always
  
networks:
  global-network:
    external: true