name: t23

volumes:
  mysql_data_volume:

services:
  db:
    image: mysql:latest
    container_name: t23-mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data_volume:/var/lib/mysql
    expose:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${MYSQL_USER}", "-p${MYSQL_PASSWORD}" ]
      interval: 30s
      timeout: 20s
      retries: 5
    networks:
      - global-network
    restart: always

  app:
    image: mick0974/a13:t23-g1
    container_name: t23-controller
    expose:
      - 8082
    depends_on:
      - db
    environment:
      DB_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}  # Usa il nome del DB definito nel .env
    networks:
      - global-network
  
networks:
  global-network:
    external: true