name: api_gateway

services:
  gateway:
    image: mick0974/a13:api-gateway
    container_name: api_gateway-controller
    expose:
      - 8090
    networks:
      - global-network
      
networks:
  global-network:
    external: true