name: t5

services:
  app:
    image: mick0974/a13:t5-g2
    container_name: t5-controller
    restart: always
    expose:
      - 8085
    networks:
      - global-network
    volumes:
      - logs:/logs  # Monta la directory dei log sul tuo host

networks:
  global-network:
    external: true

volumes:
  logs:
    external: true
