name: t4

volumes:
  pgdata:
  appdata:
  grafdata:
  promdata:

services:
  app:
    image: mick0974/a13:t4-g18
    container_name: t4-controller
    expose:
      - 8084
    volumes:
      - appdata:/app/data
      - ./config.docker.json:/app/config.json
    depends_on:
      - db
    networks:
      - global-network

  db:
    image: postgres:14-alpine3.17
    container_name: t4-postgres_db
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    ports:
      - 5432:5432
    networks:
      - global-network

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      # reference https://github.com/prometheus/prometheus/blob/main/Dockerfile
      - promdata:/prometheus
    ports:
      - 3330:9090
    networks:
      - global-network

  grafana:
    image: grafana/grafana
    ports:
      - 3300:3000/tcp
    volumes:
      - grafdata:/var/lib/grafana
    networks:
      - global-network

networks:
  global-network:
    external: true