server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  config:
    location: optional:file:.env-${spring.profiles.active}
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: root
      password: osimhen
      database: manvsclass
      port: 27017
      host: mongo_db
  datasource:
    username: root
    password: osimhen
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: gamesapp052023@gmail.com
    password: uofjilbsnraczxbk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  main:
    allow-circular-references: true
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  resources:
    add-mappings: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

logging:
  level:
    org:
      springframework:
        security: DEBUG
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

# Variabili d'ambiente per i servizi
services:
  t4:
    endpoint: ${T4_ENDPOINT:t4-controller}
    port: ${T4_PORT:8084}
  t23:
    endpoint: ${T23_ENDPOINT:t23-controller}
    port: ${T23_PORT:8082}
  t7:
    endpoint: ${T7_ENDPOINT:t7-controller}
    port: ${T7_PORT:8087}
  t8:
    endpoint: ${T8_ENDPOINT:t8-controller}
    port: ${T8_PORT:8088}

